name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  call-workflow:
    uses: ./.github/workflows/ci-common.yml
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
