name: CI

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 114

      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run tests
        env:
          CHROMEDRIVER_VERSION: 114.0.5735.16
          BROWSER_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: bundle exec rspec spec

      - name: Publish code coverage
        run: |
          export GIT_BRANCH=main
          ./cc-test-reporter after-build -r 44a8b2c6cf8d7627b384f07d3a27e73d7e12485c00eab6deeea489bca59dbdcb
